### ISSUE TITLE
Not working for "Include with where filter" 

### ISSUE THREAD

**Issue by wag900813** [ardalis/Specification#104]
Hi Sir,

![image](https://user-images.githubusercontent.com/54086306/110761459-b8a74600-828a-11eb-841a-c0a439a5a304.png)
As shown above print screen, the specification is include "BASS_REG_CITY" table with where filter REC_DELETED is active. 
![image](https://user-images.githubusercontent.com/54086306/110761746-0d4ac100-828b-11eb-8207-dba4a6767ad4.png)
The sql query generator is not joining the table "BASS_REG_CITY". Anyway to solve this? Thanks

**Comment by fiseni** [comment]
Hi @wag900813,

I crosschecked this. You can find the test [here](https://github.com/ardalis/Specification/blob/377b3c1397ec647368c9caa4420d2d9c3c893de0/ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/RepositoryOfT_ListAsync.cs#L51), and this is the produced query (to be completely sure I checked the query on SQL profiler, not only in EF logs)

![image](https://user-images.githubusercontent.com/24314310/110775287-0c9c3580-825f-11eb-8f9e-d2cbd8d35b93.png)

So, it seems it's working fine. Please follow these steps in order to troubleshoot your case
- Make sure you're using version 5.0.3 of the Specification Nuget package.
- Make sure you're using `EF Core 5`. Filtered includes were not available previously.
- Try to produce the same query with `dbContext` directly, so you can isolate the issue to the Specification package or `EF Core 5`
- I'm not quite sure, but I do think the filtered includes are available only if the navigation is a collection. In your case `BASS_REG_CITY` seems to be an owned type. Check official EF docs for that.

Once you do this, let us know if you're still having issues.

**Comment by wag900813** [comment]
Hi @fiseni ,

Thanks for the quick response. I solved it by installing latest version of ardalis.specification.entityframeworkcore nuget package and upgraded current EF core version to 5.03.

**Comment by fiseni** [comment]
Great! I'm closing the issue then.
