### ISSUE TITLE
Specification not serializable with WhereExpressions added

### ISSUE THREAD

**Issue by RussKahler1970** [ardalis/Specification#121]
I am trying to build specifications in my Blazor WebAssembly client but cannot serialize them once I add an Where linq clause.   Should I be able to serialize Specifications or do I need to build them on the server? 

here is my code: 
            var builder = new SpecificationBuilder<onca_user>(new saleSpecification<onca_user, string>());
            builder.Include<onca_user>("onca_user_phone");
            builder.Include<onca_user>("onca_user_email");
            builder.Where<onca_user>(p => p.Id == "RUSSKAHLER");
            var spec = (saleSpecification<onca_user, string>)builder.Specification;

            var text = JsonSerializer.Serialize(spec);

Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues.

**Comment by fiseni** [comment]
Hey @RussKahler1970,

How can I put this? The specifications are not designed to be used in this manner. You're way out of the comfort zone here 🙃 
My first impression is that you're trying to use specifications as a replacement for GraphQL, or as a mechanism for OData. If you want my advice, don't 😄 

Specifications contain a complex internal state (e.g. expressions), and they're not intended to be serialized. If you want your front-end side to pass the query information, you can make use of the idea of "filter" models. I think we provided few use cases in the sample app in this repository. Also, we talked on this subject during this [stream](https://www.youtube.com/watch?v=BgWWbBUWyig&t=1373s).

Let me know if this makes sense.

**Comment by RussKahler1970** [comment]
We need to support dynamic filters from the client.  We don't want to build simple filters based on a static set of properties.   I don't think GraphQL will work for us as we need to support a multi-tenant environment with each client being in its own database but using the same application.   Do you know of any projects that work in blazor webassembly offering dynamic filtering, ordering etc. that could be used to build a Specification?

**Comment by fiseni** [comment]
I do get your point. Since you're doing wasm, it means you have API endpoints on the other side. And that means you should gravitate toward minimizing the payload over the wire. Serializing complex objects and exchanging heavy information (which in most cases is not even needed) is never fun. We had similar models in the past and one way or another they all ended as a failure.

That said, your problem is not the specifications, or any other backend construct you might have. The real problem you have is the API design. Once you crack that down, the rest would follow naturally. Your requirement actually is designing queryable APIs. You not necessarily should implement it if you don't like it, but you can look and adopt some ideas from GraphQL. Also, OData is all about that, creating and consuming queryable and interoperable RESTful APIs. So, you certainly can steal whatever you like from those concepts.

Dynamic filters are much easier with dynamic languages and their corresponding frameworks (e.g. Express.js). This is somehow an issue in C#, and in any other strongly typed language. Yes, we do have model binding which makes life much easier, but still, we have to explicitly define our models which translates to defining explicit expectations in some form. The question here is what do you even mean by "dynamic filters". We tend to overgeneralize on many occasions. You might step back and think about within the scope of specific scenarios. Try to think and define the different endpoints in isolation. It might turn out that the requirements are not so generic and you can model them in a predefined way.

That's all I can say 😄 

@ardalis any smart idea here?

**Comment by RussKahler1970** [comment]
Well that gives me a lot to think about.   I am not sure if I like where my API is going at this point.  You are probably right thinking I should look at some of the queryable type approaches.  Well food for thought that is for sure.   Thanks for your time.

**Comment by fiseni** [comment]
Designing the API may seem a trivial thing, but in order to do it right, it requires careful planning. That's especially true in case of a larger app.

Should I close this issue? You're OK with the answers?

**Comment by RussKahler1970** [comment]
Yes you can close the issue.  Thanks for your help.  Yes, a strong API means everything and takes time to work through.
