### ISSUE TITLE
Adding GroupBy with post processing selector

### ISSUE THREAD

**Issue by alfredoliardo** [ardalis/Specification#138]
Hi,
I like very much repository/UnitOfWork/Specification pattern and I want to use it, but I'struggling to add support to my specification for GroupBy operation followed by a select to project custom objects.
For expample I would like to translate this query into specification pattern:

```c#     
             var entities = await _context.EntityType
            .AsNoTracking()
            .Include(e => e.NavigationProperty)
            .Where(e => e.Id == id)
            .GroupBy(g => new { g.Key1, g.Key2, g.Key3 })
            .Select(s => new CustomType{
                Property1 = s.Key1,
                Property2 = s.Key2,
                Property3 = s.Key3,
                Property4 = s.Count(),
                Property5 = s.Count(x => x.price > 10)
            }).ToListAsync();
```

Something like:
```c#
public class Specification<T> : ISpecification<T>
{
    //...
    public Expression<Func<T, object>> GroupBy {get;private set;}
    public Expression<Func<T, object>> GroupBySelector {get;private set;}
    //...
   protected virtual void ApplyGroupBy(Expression<Func<T, object>> groupByExpression, Expression<Func<IGrouping<object, T>, object> selector = null)
   {
        GroupBy = groupByExpression;
        GroupBySelector = selector;
    }
}

public class SpecificationEvaluator<T> 
{
    public static IQueryable<T> Evaluate(IQueryable<T> source, ISpecification<T> spec)
    {
         var query = source;
         //...
        if(spec.GroupBy != null){
              query = query.GroupBy(spec.GroupBy);
             if(spec.GroupBySelector != null)
                 query = query.Select(spec.GroupBySelector);
             query.SelectMany(x => x);
         }
         //...
        
        return query;
    }

}
```

**Comment by fiseni** [comment]
Hi @alfredoliardo,

The initial intention with specifications was not to get rid of custom repository methods completely, but at least to cover the simple scenarios, which usually constitutes 80% of the queries probably. Then, for all complex and aggregation queries you just add custom methods.

Honestly, I'd love to have these features implemented with specifications, but that escalates quickly 😄 The tricky part with `GroupBy` is that usually is followed with `Select` or more importantly with `SelectMany`, and the ordering how these actions are applied matters. When you directly work with `DbSet` or `IQueryable` constructs you're building them incrementally, each action adds something on top of the current state. On the other hand, the internal state of the specification is not `IQueryable`, but we keep the state as independent `Expression` or simple properties. Reconstructing all that in the intended order is not quite straightforward.

Another issue is the return types. Yes, we implemented the `Select` feature, and just because of it we have a separate construct `ISpecification<T, TResult>`. And kinda this is still a simple one since there is 1:1 mapping, and we just apply it at the end of the chain. But, that's not the case with `SelectMany`. Once you have that, then the ordering is relevant everywhere, even in pagination action.

We'll give a thought to this. I do want this too, but we'll need some free time to analyze the topic. I don't think we can implement it soon. Sorry 😞

**Comment by r2baka** [comment]
I'd like to throw my hat in the ring for Query.GroupBy(). In lieu of that, a work around for this particular scenario. Maybe I'm just missing something easy here.  Edit: I found a solution, see below. I'll keep going here, because I found this post in my search for a solution, so maybe it'll help someone else do what I was trying to do.

Here's the scenario: I have a big table with an advanced search across many fields. Some of those are drop downs. Imagine a car dealer. You can search by make, model, year, and color. If you enter a Make, then I want to get a distinct list of colors available for that make. Then I can eliminate colors from the search form where there are no cars of that color in that make, or model, or year, etc.

How do I reuse the a specification querying across a dozen fields to get the list of matching cars, to then also get a filtered list of other searchable options, like the distinct colors of those cars?

For example, the original Query might look like
```
Query.Where(car => car.Make == "Toyota");
Query.Where(car => car.Year == "2020");
Query.Where(car => car.Model == "Prius");
// etc....
```

Then, to filter the other field options:

```
Query.GroupBy(cars => 
     new { Color = colors.Color})
          .Select(c => new {Color = c.Key.Color, 
                                       CarCount = c.Sum(cars => cars.Id)}).ToList();
```
That would give me the distinct colors of Priuses.

Okay... as I was writing this, I focused on what @fiseni said, "Then, for all complex and aggregation queries you just add custom methods." So then I went back to my original CarRepository. I added a CarColors(params) method, which reused the original CarsAdvancedSearchSpecification(params) like this in the function to return a List<string> which has the colors in it.

```
var expressions = (new CarsAdvancedSearchSpecification(params)).WhereExpressions;
var colors = _dbContext.Cars.Where(c => !string.IsNullOrEmpty(c.Color));
foreach(var x in expressions)
    colors = colors.Where(x);

return colors.GroupBy(c => new {color = c.Color}).Select(c => c.Key.color).ToList(); 
```
 Anyway, I hope this helps and I'm sure it can be improved, but I couldn't find any documentation on this scenario, so here you go...

**Comment by HenricFranssonXM** [comment]
@fiseni Are there any plans GroupBy in the roadmap? Thanks!

**Comment by fiseni** [comment]
Hi All,

This is an old issue. We kept it open for a while just in case we come up with a proper solution. Unfortunately, there are too many corner cases, and it's not suitable for this library. It will be like reinventing the LINQ, which certainly is not our goal. The specifications are intended for simple scenarios, usually just for fetching entities/aggregates. For any complex read operations, you certainly would want to utilize the full potential of your ORMs. And that's also something this library is not pretending to be :)

Anyhow, the specifications can be utilized directly with DbContext, the feature that is rarely used I see. It is useful exactly for these complex scenarios.

```csharp
var spec = new CustomerSpec();
var result = await _dbContext.Customers
    .WithSpecification(spec)
    .GroupBy(x => x.Name)
    .Select(x => new CustomerInfo()
    {
        Name = x.Key,
        AverageAge = x.Average(q => q.Age)
    })
    .ToListAsync();
```

You can apply a given specification (which may contain some common conditions) and then continue building the query.

**Comment by AMIGONA100** [comment]
Adds a grouping to the query; cannot be combined with AddSelect and AddOrderBy.
... // Código BaseSpecification

public Expression<Func<T, T>>? GroupBy { get; private set; }
... // Código SpecificationEvaluator

if (spec.GroupBy != null)
{
  inputQuery = inputQuery.GroupBy(spec.GroupBy).Select(g => 
      g.First()).AsQueryable();
}
