### ISSUE TITLE
ADO.NET / Dapper compatibility

### ISSUE THREAD

**Issue by dehghani-mehdi** [ardalis/Specification#14]
Actually I'm using Dapper, is there any plan to add Dapper compatible version?

**Comment by ardalis** [comment]
Not by me but I'd welcome pull requests with it.

**Comment by ardalis** [comment]
If someone picks this up, it should be a separate project and ultimately a separate NuGet package (see #10 about moving EF to its own package)

**Comment by fiseni** [comment]
I'm not quite sure this will be possible will Dapper. It doesn't support evaluation/parsing of Expressions or IQueryable into SQL statements. The intention there was to have lightweight library so you can write your own "pure" SQL queries. There are actually extensions to Dapper that try to do that (I'm not sure how effective they are), but the authors made it clear they have no such plans.
Refer to https://stackoverflow.com/a/27588877/3813189

Possible candidates for additional plugins might be EF6, nhibernate, etc.

**Comment by fiseni** [comment]
This issue is quite old and I don't see that support for Dapper will be added. As described above, it doesn't have support, and I do think folks using Dapper are not quite interested in the abstractions provided by Specifications. On the contrary, the use Dapper to avoid such abstractions.

I'm closing the issue. If anyone shows any interest in this or wants to implement it, then feel free to re-open the issue and we can continue the discussion.
