### ISSUE TITLE
Would it be possible to extend RepositoryBase by adding a GetByIdAsNoTrackingAsync method?

### ISSUE THREAD

**Issue by dstretch** [ardalis/Specification#165]
I often want to check for the existence of an entity in the DB (to return a 404 if applicable) without tracking it so I can delete it directly afterwards if it _does_ exist.

It's great that there's now an .AsNoTracking() option in Specifications, but it's a bit of a pain having to create a Specification just for this scenario, also having to add it to every repository myself is a little tedious (first world problems I know)

Any chance of extending your handy RepositoryBase with an additional method for this?

**Comment by dstretch** [comment]
Sure, but I was trying to avoid altering the repo from the package in case
of future updates etc.

**Comment by MarkusBux** [comment]
Doing the same on my project. :) Create a custom repo that is derived from the `RepositoryBase`, extend it with all the requirements and use this own base repository to derive anything else or to use it in DI as generic repository.

That should do the trick.

Sample:
```c#
public interface IRepository<T> : IRepositoryBase<T>, IReadRepositoryBase<T> where T : class, IAggregateRoot
{
    IUnitOfWork UnitOfWork { get; }

    // some other stuff you want to use
}
```

```c#
public class MyGenericRepository<T> : RepositoryBase<T>, IRepository<T>
    where T : class, IAggregateRoot
{
    protected DomainContext Context { get; private set; }

    public EfCoreRepository(DomainContext context) : base(context)
    {
        this.Context = context;
    }

    public IUnitOfWork UnitOfWork => Context;

    // Other stuff your repository should implement/do

    /// <summary>
    /// NoOp as we want to use the UnitOwWork to save changes;
    /// As this is called within the RepositoryBase<T>
    /// we need to override it here.
    /// </summary>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    public override Task SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }
}
```

```c#
builder.Services.AddScoped(typeof(IRepository<>), typeof(MyGenericRepository<>));
```

**Comment by fiseni** [comment]
We're providing a base repository `RepositoryBase<T>` which includes some basic functionalities. It is intended to be used as a base for your own generic repository (since you have to pass in your actual DbContext). That's why we have added the "Base" suffix, so your repo can be called simply `Repository<T>`.

The users in their projects should define something as following

```c#
// Define your interface in your Core project (if you have such a solution structure).
public interface IRepository<T> : IRepositoryBase<T> where T : class
{
}

// Define this repo in your infrastructure project.
public class Repository<T> : RepositoryBase<T>, IRepository<T> where T : class
{
	private readonly SampleDbContext dbContext;

	public MyRepository(SampleDbContext dbContext) : base(dbContext)
	{
		this.dbContext = dbContext;
	}

	// Not required to implement anything. Add additional functionalities if required.
}
```

You have to do this regardless of whether you want to add something additionally or not. Once you have this, if you need extra functionalities, just add it there. Also, all methods in the built-in repo are marked as virtual, so you can override anything you want. Your request makes sense, but it's a specific use case. We want to keep the built-in repo as slim as possible.

Closing the issue. Please let us know if you have any further questions.
