### ISSUE TITLE
Combine two specifications?

### ISSUE THREAD

**Issue by ksydex** [ardalis/Specification#169]
I need to combine two independent specifications but couldn't manage to do so. Do i need to extend a class of specification or there are other options? 

Context: I have a service, with one specification i apply user context, and with second a filter, and maybe with third, a paging. Thanks.

**Comment by ardalis** [comment]
The package doesn't support arbitrary combining of specifications because many specifications can't easily be combined in any sensible way (example, a singleresult specification combined with a paging one, or two paging ones combined with different page sizes).

What you can do is leverage inheritance, for instance you could have your user context (presumably a simple Where expression) applied as an expression, and then inherit from it to extend that with additional filters.

For paging, it's not unusual to provide parameters or optional constructors on a given Specification that determine whether paging should be enabled or not.

Does that help? @fiseni has some examples of ways to use filters in a very extensible way in the sample in the repository, too, that you might find useful.

**Comment by ksydex** [comment]
> The package doesn't support arbitrary combining of specifications because many specifications can't easily be combined in any sensible way (example, a singleresult specification combined with a paging one, or two paging ones combined with different page sizes).
> 
> What you can do is leverage inheritance, for instance you could have your user context (presumably a simple Where expression) applied as an expression, and then inherit from it to extend that with additional filters.
> 
> For paging, it's not unusual to provide parameters or optional constructors on a given Specification that determine whether paging should be enabled or not.
> 
> Does that help? @fiseni has some examples of ways to use filters in a very extensible way in the sample in the repository, too, that you might find useful.

Yes, thank you!

**Comment by fiseni** [comment]
We left the possibility of combining specifications if you use them without repositories. In that case, it's possible to chain multiple specs, since each `WithSpecification` extension method usage evaluates the spec and returns `IQueryable`. The usage would be something like

```c#
dbContext.Customers.WithSpecification(new CustomerCommonSpec())
                   .WithSpecification(new CustomerByNameSpec("someName"))
                   .ToListAsync();
```

But, it would be your responsibility to be careful and to know what you're chaining and to know what can be aggregated and what can not. Some of the states can be overwritten, or you may end up with an inconsistent state of the `IQueryable`.
