### ISSUE TITLE
Efficiently return Sum (or other aggregate operations) from a Specification/Repository query?

### ISSUE THREAD

**Issue by ardalis** [ardalis/Specification#171]
If I want to return a sum value using the `BaseRepository<T>` in this package and a specification, the best I've found is to do something like this:

![image](https://user-images.githubusercontent.com/782127/139849750-017b9bf4-33b4-4482-888d-84a153be47c1.png)

This loads more data into memory than would be needed if the sum were performed in the database and just the scalar result returned.

Is there a way to achieve returning a scalar value from a query using the current repository/specification? If not, how might we support such scenarios in order to prevent the need for custom repository implementation types?

See also: 
https://github.com/dotnet-architecture/eShopOnWeb/pull/611

**Comment by fiseni** [comment]
I have thought of this and implemented few times for some personal projects. But, I didn't like the solution 😄 At best, it's not an elegant solution at all. The issue with aggregation functions like Sum, Min, Max, etc., is that you can't create a proper generic form of it. Let's take a look at the EF's IQueryable extensions.

![image](https://user-images.githubusercontent.com/24314310/139859970-73a128de-c6a0-42d4-9e59-7800a8e41be8.png)

As we can see there is overload for each primitive type. That's due to the fact that in C# we don't have a proper "primitive type" constraint for generic parameters. We can use `T : struct`, but that includes a lot more.

So, if we want to implement this, then we should also have all those overloads. The alternative would be to fall back to reflection, perhaps we might simplify it a bit in that case.

**Comment by ardalis** [comment]
Ok. I'm thinking probably the design approach I would prefer in cases where this kind of thing is needed is simply to use a different abstraction, rather than a repository. A repository is a DDD pattern designed to allow for you to deal with your entities and domain model as if they were simply available in some in memory collection. That's their intent. They're not meant to be used as an ad hoc data access layer.

If your app needs custom results from the database using custom aggregation, queries, etc. for reports or other reasons, then use a different abstraction (e.g. `IDatabaseQueryService`) and don't use an ORM for the implementation (you can still use [EF's custom SQL capability](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) if you want, but don't use its `DbSet`s).

The built-in base repository implementation does supply a `Count` method (which is an example of not returning a result in the form of domain model types) but only because that's a fairly common requirement even for entities, and it has a consistent return type.

Thoughts?

**Comment by fiseni** [comment]
Yes, I do agree with that. We added the `Count`, just because of its simplicity and the common usage (e.g. for pagination).
As you already stated, these types of actions somehow fall into the category of reporting, or at least for some really specific usages. And for such scenarios, you may have different infrastructure and an additional set of abstractions.

The question here is whether we see this as part of the specifications or not? I'm not quite sure about that. First, keeping that state might be fuzzy. And most importantly these aggregation functions are actually "materializing" actions. It means they are called at the end of the chain where you need to materialize the content of `IQueryable` and get the final result. So they're at the level of `FirstAsync`, `ListAsync`, `CountAsync`, etc. Consequently, it should be part of your materializing abstraction (in our case the repositories), and not as part of the spec.

**Comment by ardalis** [comment]
I don't think we have any plans to implement something like this.
