### ISSUE TITLE
Capacity to Extend to have a composite specification

### ISSUE THREAD

**Issue by ygo74** [ardalis/Specification#225]
Hello,

I tried your specifications => It's a great job. I like it and found you did a professional library ready to be used in enterprise

I like also composite specifications with fluent capacity

How can I extend your specifications to Add this behavior. 
I would like to have the following style
```csharp
var specification = SpecificationFactory<Customer>.Create()
                        .LiveInCountry("FRANCE")
                        .OlderThan(18);
```

I think It could be interesting for advanced filters scenarios

I will be happy if you can help me,  could you say me if it is possible and how do I start / implement this extension ?

Best regards

**Comment by ardalis** [comment]
On the surface I like it, but after thinking about it for a moment, I question how a custom SpecificationFactory offers a better experience than just using LINQ with your entity?

```csharp
var query = db.Customers
                   .Where(c => c.Country == "FRANCE")
                   .Where(c => c.Age >= 18);
```

The point of the Specification pattern is that it's a reusable, concrete part of your domain model. The infinite flexibility of a builder like this would eliminate this value, and would shift business and query logic to wherever the builder was being used, rather than keeping it in the Specifications (and in the domain model) itself.

@fiseni thoughts?

                   
```

**Comment by fiseni** [comment]
Well, there are various implementations. Your example is not really about composite specifications. It seems it starts with an empty Customer specifications, and then you build it on the go. Personally, I'm not a fan of this approach. Instead of having LINQ statements all over your code, you end up having glorified LINQ statements all over you code. But, the end result is kind of same perhaps?

Our specifications are not designed to be altered after their creation. But, if you wanna use it this way, then here you have a full example.

```c#
using Ardalis.Specification;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var spec = new CustomerSpec()
                        .LiveInCountry("FRANCE")
                        .OlderThan(18);
        }
    }

    public class Customer
    {
        public string Country { get; set; }
        public int Age { get; set; }
        public List<Address> Addresses { get; set; }
    }

    public class Address
    {
        public string Street { get; set; }
    }

    public class CustomerSpec : Specification<Customer>
    {
        public CustomerSpec()
        {
            // Have your initial query here. Or it may be completely empty as well.
            Query.Include(x => x.Addresses);
        }
    }

    public static class MySpecificationExtensions
    {
        public static ISpecification<Customer> LiveInCountry(this ISpecification<Customer> specification, string country)
        {
            ((List<Expression<Func<Customer, bool>>>)specification.WhereExpressions)
                .Add(x => x.Country.Equals(country));

            return specification;
        }

        public static ISpecification<Customer> OlderThan(this ISpecification<Customer> specification, int age)
        {
            ((List<Expression<Func<Customer, bool>>>)specification.WhereExpressions)
                .Add(x => x.Age > age);

            return specification;
        }

    }
}

```

**Comment by fiseni** [comment]
@ygo74 Are you happy with the answer? Should we close the issue?

**Comment by fiseni** [comment]
As I mentioned in the previous comment, our specifications should be considered immutable (that's why the state is exposed as IEnumerable). They are not intended for further modification once they are created. So, in your case, you usually will have a separate specification as follows

```c#
public class CustomerByCountryAndAge : Specification<Customer>
{
    public CustomerByCountryAndAge(string country, int age)
    {
        Query.Where(x => x.Country.Equals(country))
            .Where(x => x.Age > age);
    }
}
```

Yes, casting isn't nice, since it implies you know the underlying type of the collection and we may change that implementation in the future. I provided just a hack for your desired usage.

**Comment by fretje** [comment]
Case in point... shouldn't it be

```c#
    ((List<WhereExpressionInfo<T>>)specification.WhereExpressions)
        .Add(new WhereExpressionInfo<T>(criteria));
```
now?

**Comment by fiseni** [comment]
Yes, that's right. My example was based on version 5. Just recently version 6 was published, where we defined separate types holding info for these expessions (so we can keep compiled versions for in-memory evaluators).

**Comment by fretje** [comment]
I really like how you always give very detailed and clear answers (even though my comment was more of the rhetorical kind ;-)).

Also really like the project and design of it btw! Keep it on!

**Comment by ygo74** [comment]
Hello
Yes of course I'm happy with the answer.
I tested it with this Generic Implementation

```csharp
    public static class SpecificationExtension
    {
        public static ISpecification<T> And<T>(this ISpecification<T> specification, ISpecification<T> right) where T : class
        {


            ((List<Expression<Func<T, bool>>>)right.WhereExpressions).ForEach(expression =>
            {
                ((List<Expression<Func<T, bool>>>)specification.WhereExpressions).Add(expression);
            });

            return specification;

        }

    }
```

and I can use it in this way

```csharp
            // Arrange
            var servers = ServerSeed.Get();
            var spec = new ServerByOSReadOnlySpec(OsFamily.Windows).And(new ServerByActiveStatusReadOnlySpec());

            // Act
            var result = spec.Evaluate(servers).ToList();

            // Assert
            Assert.IsNotNull(result);
            Assert.IsTrue(result.Count > 0);
```

Now I Have to see if it is possible to do the same for Or Operator

Thank you for your help
