### ISSUE TITLE
Add an AddRangeAsync to IRepositoryBase

### ISSUE THREAD

**Issue by chadboettcher** [ardalis/Specification#234]
Would it be possible to add an AddRangeAsync method to IRepositoryBase. There is already a DeleteRangeAsync and it could be convenient to be able to do a bulk add.

Thanks,

Chad

**Comment by fiseni** [comment]
See issue #233 

Well, it's a rabbit hole 😄 But, since we already added for Delete (perhaps someone requested it), I guess we should be fair and do it for Add too in the next release.

We considered moving the repository stuff in separate packages. I don't know how that will play out, it might confuse the users even more. We'll need `Ardalis.Repository.Abstraction`, `Ardalis.Repository.EntityFrameworkCore`, `Ardalis.Repository.EntityFramework6`. Those provider packages perhaps should depend on `Ardalis.Specification.EntityFrameworkCore`/`Ardalis.Specification.EntityFramework6`. So, it might do more harm than good and add to the confusion.

**Comment by ardalis** [comment]
Yeah I think you talked me out of making a separate Repository package. :)

I wonder if it would make sense to have `RepositoryBase` with really basic functionality and then `RepositoryExtendedBase` with more of these "extra" feature requests that are more "nice to have" than required...

**Comment by chadboettcher** [comment]
That would be awesome as that's more or less what we're trying to do (with some difficulty) now that you've framed those two projects as examples.

**Comment by ardalis** [comment]
That would be a breaking change, though, so will probably wait until next version.

In the meantime we could probably add this one. Anybody want to PR it?

**Comment by fiseni** [comment]
Implemented. Closing.
