### ISSUE TITLE
New version has broken the unit tests

### ISSUE THREAD

**Issue by sahinad** [ardalis/Specification#235]
Hi,

After I have upgraded from the version 5 to 6, my specification unit tests are broken.

![image](https://user-images.githubusercontent.com/22755247/151456424-0cc642ca-c1ef-4a92-8c79-69727b87b759.png)

I couldn't find an example in the docs. Any idea?

Thanks,
Adem

**Comment by ardalis** [comment]
It's .Filter now I think.

**Comment by r2baka** [comment]
It is .Filter, yes.  spec.WhereExpressions.FirstOrDefault().Filter

I'm not seeing the .Select() Capability to limit the columns that come back from the DB Server though. Is that in this release? 

See this for reference:
https://github.com/ardalis/CleanArchitecture/issues/148

**Comment by sahinad** [comment]
> It's .Filter now I think.

Yes, it's working now. Thank you.

**Comment by sahinad** [comment]
> It is .Filter, yes, I can confirm that as I just did it today. spec.WhereExpressions.FirstOrDefault().Filter
> 
> I'm not seeing the .Select() Capability to limit the columns that come back from the DB Server though. Is that in this release?
> 
> See this for reference: [ardalis/CleanArchitecture#148](https://github.com/ardalis/CleanArchitecture/issues/148)
> 
> I can't find the samples for that either.

I had a similar problem with the .Select() functionality. I solved it by creating a separate repository. Couldn't use the specification for it.

**Comment by fiseni** [comment]
Yes, there are breaking changes. We mentioned them in the release notes [here](https://github.com/ardalis/Specification/releases/tag/v6.0.0). The state for `WhereExpressions`, `OrderExpressions`, `SearchCriterias` are stored in separate types which hold the original expression and the compiled one (used for in-memory evaluators).

As for the `Select` functionality, there are no breaking changes. But, in order to use that feature, you have to define a specification with a return type. We've done that so users don't accidentally apply `Select` for specifications that don't have return type defined. This behavior is not new.

```c#
public class Customer
{
    public string Name { get; set; }
}
public class CustomerSpec : Specification<Customer, string>
{
    public CustomerSpec()
    {
        Query.Select(x => x.Name);
    }
}
```
