### ISSUE TITLE
Question about sub entities

### ISSUE THREAD

**Issue by DannyBoyNg** [ardalis/Specification#256]
There is something I just can't figure out and I can't find any documentation on it. Lets say I have two entities, an Order and an OrderItem. Order is the AggregateRoot and OrderItem is the sub entity.

When I add or modify a few OrderItems and I do an UpdateAsync on Order, everything works perfectly. All modified OrderItems get updated and new OrderItems get inserted automatically.

When I remove an OrderItem from an Order and I do an UpdateAsync on Order, the OrderItem does not get deleted from the database. Maybe this behavior is intended because you don't want to delete OrderItems on accident when you are just updating a RootEntity.

My question is, how do I delete sub entities? Do I make OrderItem a RootAggregate also? That seems wrong to me, please help me figure this out.

I'm using Ardalis.Specification version 6.0.1

**Comment by DannyBoyNg** [comment]
I found out that the OrderItems that I want to remove are not tracked by Entity Framework Core. So EF Core has no way to know which OrderItems to delete. This should be easy to solve when you have access to the DbContext but how do I solve this using the Specification Pattern?

**Comment by jdrames** [comment]
@DannyBoyNg : how are you defining your OrderItem?
I found that as long as I have a reference to the Order Id things work fine. Just don't include it in the constructor method for OrderItem as it'll be created/added by EF.

```
public class Order : BaseEntity, IAggregateRoot
{
    ...
    private readonly List<OrderItem> _orderItems = new();
    public IEnumerable<OrderItem> OrderItems => _orderItems.AsEnumerable();

    public void RemoteOrderItem(OrderItem orderItem){
        Guard.Against.Null(orderItem, nameof(orderItem));
        _orderItems.Remove(orderItem);
    }
}


public class OrderItem : BaseEntity
{
    ...
    public int OrderId {get; private set;}
    ...
}
```

Then in the DbContext include:
public DbSet<Order> Orders {get ;set; }
public DbSet<OrderItem> OrderItems {get; set;}

**Comment by jdrames** [comment]
Additionally this is also how I fixed an issue where deleting an Order wouldn't Cascade Delete the OrderItems in the db. Instead it was just nulling out the key column.

**Comment by DannyBoyNg** [comment]
Thanks @jdrames, I think you just answered my question. I just have to add extra methods to my Order entity. For some reason I did not think about doing that. thanks for your help!

**Comment by DannyBoyNg** [comment]
Hi @jdrames , I changed my Order and OrderItem to the example you showed me, since EF Core creates them a little differently. I also added an extra method RemoveOrderItem inside Order but... just removing an item from the _orderItems List does not actually delete the items from the database. I think I'm missing something small. Do you have any idea what I'm missing.

I'm using the Specification Pattern combined with the Generic Repository Pattern.

**Comment by DannyBoyNg** [comment]
I found a way to make it work. If I make OrderItem an IAggregateRoot, I can easily delete the OrderItems I need to delete because it would let me create a generic repository for OrderItem. The problem with this solution is that basically every entity becomes an IAggregateRoot. I'm afraid this is not following the Specification Pattern. Please correct me if I'm wrong. I would like to find the proper way of solving this problem.

**Comment by fiseni** [comment]
Hey @DannyBoyNg,

This issue is not directly related to this library. This has to do with how have you configured your relationships. This is the default behavior:
- If the `OrderItem` has nullable FK to `Order`, then when `Order` is deleted, the `OrderItems` is not deleted, only FK is set to null.
- If the `OrderItem` has required FK to `Order`, then when `Order` is deleted, the `OrderItems` are deleted too.

How can you alter the default configuration of EF? Here are a few options:
- Explicitly add "OrderId" property in `OrderItem`. If the property is of not nullable type (int, Guid, etc.), the EF will configure it as a required relationship.
- You can explicitly configure this relationship
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Order>().HasMany(x => x.OrderItems).WithOne().IsRequired(true);
}
```
- You can leave the FK nullable and explicitly configure what happens on Delete action
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Order>().HasMany(x => x.OrderItems).WithOne().OnDelete(DeleteBehavior.Cascade);
}
```

You don't need to delete the OrderItem directly, so you don't need `OrderItem` DbSet, neither you need a repository for it. Deleting it from `Order`'s collection is enough. But, while fetching the `Order` you have to fetch it with `OrderItems`, so you have to include that navigation.

If you face issues, please provide the link to your repository, so we can see exactly what you're dealing with.

**Comment by DannyBoyNg** [comment]
Hi @fiseni, thank you so much for your tips. The problem seemed to be somewhere different. In the order specification file I used the following: Query.AsNoTracking().Where(x => x.Id == orderId).Include(x => x.OrderItems);

Removing the .AsNoTracking() fixed the problem for me. Everthing just worked. I knew I was doing something really silly.
