### ISSUE TITLE
How can one define the Selector?

### ISSUE THREAD

**Issue by jaywork2020** [ardalis/Specification#259]
Hello,
I am trying to use this project in my code. I am getting 

> SelectorNotFoundException Ardalis.Specification.SelectorNotFoundException: The specification must have Selector defined

I created the following specification

```
public class ProductByIdsSpec : Specification<Product, ProductMenuItem>
{
    public ClientRecordByIdsSpec(IEnumerable<int> ids)
    {
        if (ids == null || !ids.Any())
        {
            return;
        }

        Query.Where(x => ids.Contains(x.Id));


        // some how I need to map Product to ProductMenuItem so only the needed columns are pulled from the database.
    }

}
```

How would I add the map between entity (i.e., `Product`) and and the result object (i.e., `ProductMenuItem`)?

I tried to add `Select()` definition but I get the same results

```
public class ProductByIdsSpec : Specification<Product, ProductMenuItem>
{
    public ClientRecordByIdsSpec(IEnumerable<int> ids)
    {
        if (ids == null || !ids.Any())
        {
            return;
        }

        Query.Where(x => ids.Contains(x.Id));


        Query.Select(x => new ProductMenuItem() { Name = x.Name, x.Id = x.Id });
    }

}
```

**Comment by paul-charlton** [comment]
@jaywork2020 i know it's been a couple of yesr but did you find a solution to this?

**Comment by paul-charlton** [comment]
> @jaywork2020 i know it's been a couple of yesr but did you find a solution to this?

Turns out the above works, i was trying to fluently chain Query.Where().Select() which wouldn't compile.

**Comment by ardalis** [comment]
Right, you can't chain it from .Where currently; it needs to be a separate call off of Query.

**Comment by ardalis** [comment]
@fiseni is this something you want to improve?

**Comment by kawazoe** [comment]
Hi, I just stumbled upon this issue while trying to run a query with an OrderBy against a projected value. Your last comment comes at the right time. Essentially, I'm trying to convert a piece of LINQ similar to this into a Specification:

```
var anArgument = ...;
var results = source
  .Select(value = new { value, computed = value.someProp == anArgument } )
  .OrderBy(v => v.computed)
  .ThenBy(v => v.value.otherProp)
  .Select(v => v.value);
```

The `computed` value is only needed for the query and is never exposed to the caller later on, but is needed inside the query for the OrderBy clause. Since it depends on a dynamic argument, this value cannot be pre-computed in a way that could include it in the source entity. It also doesn't make much sense to do so, since it isn't meant to be exposed.

I do not think this is possible with the current design for Select in Specifications, and would like if an improved version could support this scenario.

**Comment by fiseni** [comment]
Hi @jaywork2020,

Sorry for being a year late here :)

What you have is perfectly fine

```c#
public class ProductByIdsSpec : Specification<Product, ProductMenuItem>
{
    public ClientRecordByIdsSpec(IEnumerable<int> ids)
    {
        if (ids == null || !ids.Any())
        {
            return;
        }

        Query.Where(x => ids.Contains(x.Id));

        Query.Select(x => new ProductMenuItem() { Name = x.Name, x.Id = x.Id });
    }
}
```

But, I suspect you're missing the required method overloads that Return `TResult` in your repository. You should have the following methods. Also, refer to our [RepositoryBase](https://github.com/ardalis/Specification/blob/main/Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs) as an example.

```c#
public virtual async Task<TResult?> FirstOrDefaultAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken = default)
{
  return await ApplySpecification(specification).FirstOrDefaultAsync(cancellationToken);
}

public virtual async Task<TResult?> SingleOrDefaultAsync<TResult>(ISingleResultSpecification<T, TResult> specification, CancellationToken cancellationToken = default)
{
  return await ApplySpecification(specification).SingleOrDefaultAsync(cancellationToken);
}

public virtual async Task<List<TResult>> ListAsync<TResult>(ISpecification<T, TResult> specification, CancellationToken cancellationToken = default)
{
  var queryResult = await ApplySpecification(specification).ToListAsync(cancellationToken);

  return specification.PostProcessingAction == null ? queryResult : specification.PostProcessingAction(queryResult).ToList();
}
```

Once you add those methods, then the result you get will be of type `TResult`, in your case `ProductMenuItem`.

**Comment by fiseni** [comment]
Hi @kawazoe,

No, that won't be possible. We're keeping the specification state in form of expressions. In yourcase, you need to work on top of `IQueryable` since you need to build the query incrementally.

The specifications are designed for simple queries and cover most of your common queries. Whenever you need something more complex, just create separate Query objects and work directly with your ORM or DB. Btw, you still can leverage the specifications there. For instance, you may apply the base requirements, and then continue building the query.

```c#
var anArgument = ...;
var results = _dbContext.Customers
  .WithSpecification(someSpec)
  .Select(value = new { value, computed = value.someProp == anArgument } )
  .OrderBy(v => v.computed)
  .ThenBy(v => v.value.otherProp)
  .Select(v => v.value);
```
