### ISSUE TITLE
Cannot use value object as criteria in specification.

### ISSUE THREAD

**Issue by rsoulard-cadenza** [ardalis/Specification#279]
### Information
**Version:** 6.1.0
**Using:** .Net 6, EF Core 6.0.6

### Description
When creating a specification with a value object (provided below), a receive the following error:
```
System.InvalidOperationException : No backing field could be found for property 'Address.PlaceEntityId' and the property does not have a getter.
```

When performing an equivalent call in on the raw queryable, such as:
```C#
var result = await applicationDbContext.Set<PlaceEntity>().AnyAsync(place => place.Address == address);
```
There is no exception thrown and the code runs as expected. I would expect code run through the equivalent specification to do the same. I understand that the exception is asking for there to be a provided field, but again, raw queryable handles this without the exception and I may want to reuse this value object elsewhere with other entities.

**ValueObject.cs** 
```C#
public abstract class ValueObject
{
    protected static bool EqualOperator(ValueObject left, ValueObject right)
    {
        if (ReferenceEquals(left, null) ^ ReferenceEquals(right, null))
        {
            return false;
        }

        return ReferenceEquals(left, right) || left.Equals(right);
    }

    protected static bool NotEqualOperator(ValueObject left, ValueObject right)
    {
        return !EqualOperator(left, right);
    }

    protected abstract IEnumerable<object?> GetEqualityComponents();

    public static bool operator ==(ValueObject left, ValueObject right)
    {
        return EqualOperator(left, right);
    }

    public static bool operator !=(ValueObject left, ValueObject right)
    {
        return NotEqualOperator(left, right);
    }
    
    public override bool Equals(object obj)
    {
        if (obj == null || obj.GetType() != GetType())
        {
            return false;
        }

        var other = (ValueObject)obj;

        return this.GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());
    }

    public override int GetHashCode()
    {
        return GetEqualityComponents()
            .Select(x => x != null ? x.GetHashCode() : 0)
            .Aggregate((x, y) => x ^ y);
    }
}
```

**Address.cs**
```C#
public class Address : ValueObject
{
    public string? Street { get; private set; }
    public string? City { get; private set; }
    public string? State { get; private set; }
    public string? Country { get; private set; }
    public string? ZipCode { get; private set; }
    public string? Other { get; private set; }

    public Address()
    {
    }

    public Address(string street, string city, string state, string country, string zipCode, string? other)
    {
        Street = street;
        City = city;
        State = state;
        Country = country;
        ZipCode = zipCode;
        Other = other;
    }

    protected override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Street;
        yield return City;
        yield return State;
        yield return Country;
        yield return ZipCode;
        yield return Other;
    }
}
```

**PlaceSpecification.cs**
```C#
public class PlaceSpecification : Specification<PlaceEntity>
{
    public PlaceSpecification(Address address)
    {
        Query.Where(place => place.Address == address);
    }
}
```

PlaceEntity and Address are linked as follows:
```C#
        builder.Entity<PlaceEntity>(entity =>
        {
            entity.OwnsOne(place => place.Address);
        });
```

### Workaround
Breaking down the criteria to compare each property of the value object works, but is redundant as this work is already handled as part of ValueObject and Address.

**PlaceSpecification.cs**
```C#
public class PlaceSpecification : Specification<PlaceEntity>
{
    public PlaceSpecification(Address address)
    {
        Query.Where(place =>
            place.Address.Street == address.Street &&
                place.Address.City == address.City &&
                place.Address.State == address.State &&
                place.Address.Country == address.Country &&
                place.Address.ZipCode == address.ZipCode &&
                place.Address.Other == address.Other
        );
    }
}
```

**Comment by fiseni** [comment]
Hi @rsoulard-cadenza,

Thank you for your detailed explanation. I really do appreciate it when the issues are elaborated on in this manner.

Unfortunately, the issue is not related to this library. You will get the same exception even when working directly with `DbContext`. To convince you, I created a sample application using your code https://github.com/fiseni/SpecVoIssue.

There are two endpoints. You will get the same exception in both cases.
- /places/ef       - It uses EF directly
- /places/spec   - It uses a specification

Actually, this is expected behavior. EntityFramework Core doesn't have support for value objects. We, the community, are using `Owned Entities` just as a workaround. But, we should be aware that in fact it's just a workaround, and there are issues with that approach. The `Owned Entities` were designed with a different aim, to implement the concept of the aggregates. That said, EF considers them as entities; and even though you have not defined an FK property, the EF will generate that internally. If you debug the code and examine the `ChangeTracker`, you would be surprised to see a `PlaceId` field for the `Address` object. Aside from the issue you're facing, you also should be aware of the following:

```
// Here you might expect that once saved, both place1 and place2 will have the same address.
// But, if you do this, you'll get either an exception or place2's address will be deleted.
// That's the case since Address has a PlaceId FK assigned, and can be related to a single entity. Hence the name Owned entities.

place1.Address = place2.Address
```

Luckily, in `EF Core 7` we will get native support for value objects. Here is the [announcement](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#value-objects).

**Comment by rsoulard-cadenza** [comment]
Hello @fiseni !

I appreciate the thorough and polite response. When I had tested the dbContext side of things, I did so in an intermediate window. Altering my code to do what you did in your example does prove that you are in fact correct, it will fail.

...but for reasons that don't warrant an answer here it DOES work in an intermediate window. (See screenshot). For now, I will close this ticket. 

Again thank you for the response.
<img width="641" alt="Screen Shot 2022-07-14 at 4 51 46 PM" src="https://user-images.githubusercontent.com/82470564/179084391-1dd022fa-38f8-4663-ab0c-8c6195b9ca73.png">
