### ISSUE TITLE
Should I be trapping for DBUpdateConcurrencyException ?

### ISSUE THREAD

**Issue by tmakaro** [ardalis/Specification#284]
I see that the Ardalis.Specification.EntityFrameworkCore.RepositoryBase<T> calls DbContext.SaveChangesAsync(cancellationToken).
What happens if this method throws a DBUpdateConcurrencyException and I want to trap that in my domain? To do that my domain code has to reference Microsoft.EntityFrameworkCore which I shouldn't do in my domain.

What would be the best way to handle this?
IMO, the RepositoryBase<T> should catch DBUpdateConcurrencyException and then return a custom exception that is not linked to EF Core.

**Comment by jasonsummers** [comment]
Hi @tmakaro,

I agree with your opinion - any errors, exceptions or otherwise, should be kept within the boundary of the Infrastructure layer.
Defining the mechanism for how the Infrastructure layer reports successes or failures back to the Domain or Application layers depends on how much information your Domain / Application layers need, some of the builtin exceptions may do the job but similarly you might want to create a custom exception in your SharedKernel. You might even chose to just return a boolean to indicate success or failure.

Hope that helps.

**Comment by muratyuceer** [comment]
Can't you override savechanges method in dbcontext to handle that

**Comment by ardalis** [comment]
In your Repository, you can add the necessary try-catch logic to catch this specific exception, and then throw a new exception that is not specific to the data access provider you're using (defined in your domain model, ideally). In this way you can still know about the exception but not have direct coupling between your domain and your infrastructure implementation details.
