### ISSUE TITLE
SelectMany option for Specification<T, TResult>

### ISSUE THREAD

**Issue by MGramolini** [ardalis/Specification#294]
It would be useful to be able to do a SelectMany and I believe it would not take much effort to add.  I would be willing to make the adjustments if it would be considered.

**Comment by MisinformedDNA** [comment]
I'm hitting a major performance issue. I'm currently querying an aggregate and its entities, but the DbContext is getting bloated and causing slow performance. My thought was to write two specs, one that queries the aggregate with `AsNoTrackingWithIdentityResolution()` and the other to query the entity, through the aggregate and the use of `SelectMany()`. I can't query the entity directly because my `IRepository` only works with aggregates.

I could ditch `Specification` for this scenario but having `SelectMany()` would make my life much easier.

@ardalis @fiseni ?

**Comment by fiseni** [comment]
Hi,

Yea, it would be great. Wanna give it a shot? @MGramolini ?

It's a bit of a problem though. Users might think that they can chain multiple `SelectMany` and `Select` statements, and that won't be the case. Yes, we're chaining various other methods, but we're just building the specification state. In the case of projections (the `Select` variants), the return type is a new type. But, the input to the next method will still be the entity in our case. So, it will be a bit confusing.

**Comment by ardalis** [comment]
If someone wants to take on adding SelectMany support to the library, we're open to a pull request for it!

**Comment by amdavie** [comment]
I also have a need for SelectMany. I haven't seen any traffic on this for a while, so I'm willing to attempt a PR if no one else has started work on this.

**Comment by stefannikolei** [comment]
Any plans for a release in the near future with thsi feature?

**Comment by fiseni** [comment]
Yes, in the next two weeks, around 15th May.

**Comment by fiseni** [comment]
Closing the issue, the feature is published in version 7.
