### ISSUE TITLE
.NET 7 Support

### ISSUE THREAD

**Issue by dsolteszopyn** [ardalis/Specification#300]

**Comment by fiseni** [comment]
We'll publish a release soon, waiting for some fixes in `EF Core 7.0.2`.

Btw, nothing prevents you to consume the library in `.NET7`. The library defines only the minimum version requirements, you're free to use newer versions of the dependencies. All you need is to just explicitly install the EF Core Nuget package, and the dependencies will be updated accordingly.

![image](https://user-images.githubusercontent.com/24314310/215791448-7f8045ea-a013-41f5-80c8-db3597f1f96b.png)

@ardalis I'm not even sure whether we should update to `EF Core 7`. We should update the plugin package dependency only if there are features in the newer version that we want to utilize. Otherwise, no real benefit in doing so. On contrary, needlessly we'll force consumers to update to `EF Core 7`.

**Comment by ardalis** [comment]
.NET 7 is supported.
