### ISSUE TITLE
Spec with AsNoTracking , and RepositoryBase<T>

### ISSUE THREAD

**Issue by raphael-theriault** [ardalis/Specification#309]
Hi, 

I have realized that using a specification with AsNoTracking, will have no effect on the use of IRepository with any RepositoryBase's methods. 
I know it sounds idiot to select an entity with AsNoTracking and then later try to update it with UpdateAsync.  But, the idea behind this is,  I don't want anybody to change anything in a particular entity.  
Every method in RepositoryBase starts with the tracking of the entity. 
should we just add a state check just before that? and throws if the entity is "Detached"?
Or am I missing something else in the portrait of my understanding?

Thanks

**Comment by fiseni** [comment]
Hi @raphael-theriault,

I didn't understand exactly what you are trying to achieve. The methods in the repository start with the `DbSet`, and then the specification is applied. If the specification contains `AsNoTracking` then it will be added to the query, otherwise, it won't.

If you want to avoid consumers updating the entities, then just use the `IReadRepositoryBase`. That contract doesn't have the Add, Update, Delete methods. If you have a very specific use case, then you can create your own contract and include whatever you need.

**Comment by raphael-theriault** [comment]
@fiseni Thank you for your time.  Will use IReadRepositoryBase.
