### ISSUE TITLE
Testing with Specifications

### ISSUE THREAD

**Issue by tbalasavage** [ardalis/Specification#314]
Do you have any examples of unit tests that include specifications? For instance, if you were to test the [CustomerUIService](https://github.com/ardalis/Specification/blob/main/sample/Ardalis.SampleApp.Web/Services/CustomerUiService.cs), which includes `new` Specifications, what might that look like? Do you need to setup a database or can it be done in memory?

**Comment by fiseni** [comment]
Hi @tbalasavage,

First, you can test your specification criteria in isolation. Let's say you have the following spec.

```c#
public class CustomerInTheirTwentiesSpec : Specification<Customer>
{
    public CustomerInTheirTwentiesSpec() 
    {
        Query.Where(x => x.Age >=20 && x.Age < 30);
    }
}
```
Here is a sample test
```c#
[Fact]
public void ReturnsOnlyCustomersInTheirTwenties()
{
    var customers = new[]
    {
        new Customer {Age = 20},
        new Customer {Age = 24},
        new Customer {Age = 30},
        new Customer {Age = 31},
        new Customer {Age = 29},
    };

    var spec = new CustomerInTheirTwentiesSpec();

    var result = spec.Evaluate(customers);

    result.Should().NotBeEmpty();
    result.Should().HaveCount(3);
}
```

As for your question, about whether you need to mock the `new spec()` in your services, the answer is No. The specifications are not "actuators", they don't have any side effects, they are just "data constructs". In your example, if you want to mock persistence, then you would mock your repository methods, so they also return a predefined set of data.

Does that answer your question?

**Comment by ardalis** [comment]
Closing for now; reopen if you have more questions.

**Comment by ppvario** [comment]
@ardalis do you have any suggestion on how to unit test these specifications when they have EF.Functions.Like in the query?

The above method results into the following error:
System.InvalidOperationException: 'The 'Like' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.'

**Comment by ardalis** [comment]
No, I normally use integration tests for anything that uses EF Core and/or database operations.
