### ISSUE TITLE
Request to multi-target EntityFramework6.csproj and include net6.0

### ISSUE THREAD

**Issue by mpickers** [ardalis/Specification#340]
We have a code base in net6.0 (migrated from net framework 4.8) but still use Entity Framework v6.

We were hoping to use the Specification nuget to update some sections of code, but noticed that Ardalis.Specification.EntityFramework6.csproj only targets **framework 4.7.2**

EF6 targets NetStandard2.1 so there shouldn't be a reason the Ardalis.Specification.EntityFramework6.csproj can't also target net6.0

The only issue would be AsAsyncEnumerable() would have to throw a NotImplementedException() or NotSupportedException() for the RepositoryBaseOfT EF6 implementation, eg 
```
#if NET6_0_OR_GREATER
    /// <summary>
    /// Finds all entities of <typeparamref name="T" />, that matches the encapsulated query logic of the
    /// <paramref name="specification"/>, from the database.
    /// </summary>
    /// <param name="specification">The encapsulated query logic.</param>
    /// <returns>
    ///  Returns an IAsyncEnumerable<T> which can be enumerated asynchronously.
    /// </returns>
    public virtual IAsyncEnumerable<T> AsAsyncEnumerable(ISpecification<T> specification)
    {
      throw new NotImplementedException();
    }
#endif
```

However, it still allows others to override it and implement their own version of it if they so desire. eg something like https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.cs

**Comment by fiseni** [comment]
Hi @mpickers,

We might do this. There is no need to throw an exception, that method won't exist at all in the EF6 package. It will reference the `netstandard2.0` TFM of `Ardalis.Specification`, and we have excluded this method in the interface for this TFM.

```
#if NET6_0_OR_GREATER
  IAsyncEnumerable<T> AsAsyncEnumerable(ISpecification<T> specification);
#endif
```

Probably we can do this change for the next release. We just have to think once again whether we're breaking any consumer.

**Comment by fiseni** [comment]
Hey @mpickers,

We can't target `netstandard2.1`. Consumers will face runtime issues. For instance, if you consume the libraries from `.NET6`, and you have the following code (which you must have actually), then you'll face a peculiar issue. Since the base package targets `.NET6 ` the `AsAsyncEnumerable` method in the interface will be enabled. On the other hand, the `EF6` package compiled in `.netstandard2.1` won't see it and the repo implementation will compile without it. Hence on runtime, you'll get an exception.

```csharp
public class Repository<T> : RepositoryBase<T> where T : class
{
    public Repository(TestDbContext dbContext) : base(dbContext)
    {
    }
}
```

Anyway, we can target `NET6` for `EF6` package. In that case, indeed we have to throw `NotImplementedException`.

Are you ok with this?

**Comment by mpickers** [comment]
@fiseni Yes, that would be perfect, thanks. I suggested targeting net6. The netstandard2.1 comment was just stating that EF6 was "able" to be used by net6 projects.
