### ISSUE TITLE
How to combine specifications?

### ISSUE THREAD

**Issue by LiptonDev** [ardalis/Specification#379]
Hello. How to combine 2 or more specification in 1 specification?
I just don't know what to do with my specs if I want to reuse existing specs like:
- first specification: find user by id
- second specification: find a user when he is not blocked
- third specification: find the user who has the specified role

I want use this like: 
```c#
UserSpec.FindById(1) && UserSpec.NotBlocked && UserSpec.HasRole("admin")
```

Where UserSpec.HasRole is:

```c#
public class UserHasRoleSpecification : Specification<ApplicationUser>
{
    public UserHasRoleSpecification(string role)
    {
        Query.Where(x => x.Roles.Contains(role)); //roles - other table in db
    }
}
```

How to combine these specs into one or this library doesn't know how to do that?

p.s. - sorry for my English

**Comment by ardalis** [comment]
We don't recommend or support combining specifications, because doing so moves query logic out of the domain model and into the consumer (typically UI) layer. Instead, if you have predicates you want to share, these can be shared between Specifications by simply creating (static) properties of type `Func<T,bool>` and then using these within your well-named specifications.

One (other) reason we don't support arbitrarily combining specs is that they often include more than just a predicate. So if you have a specification that includes OrderBy, and a second one that orders by something else, which one would "win"? The right approach is to just extract the predicate logic (if needed) and reuse that between specifications but within your domain model.

**Comment by jvmlet** [comment]
Thanks for the answer, but I'm not sure  how combing predicates moves logic out from domain, can we at least combine the **predicates** (Query) from 2 specs?
````c#
new Spec1().
WithQueryFrom(new Spec2()).
WithQueryFrom(new Spec3())
````

**Comment by ardalis** [comment]
Yes, see my updated comment above.

**Comment by ardalis** [comment]
Right but that would still encourage client code to compose data access logic from some arbitrary combination of specifications, possibly involving AND, OR, and NOT. At which point you might end up with arbitrarily complex logic that isn't in the domain model but is instead in the UI layer where it doesn't belong.

If you need Spec1 with filters from Spec2 and Spec3 then my recommendation is to move those filters to predicates and then reference those predicates from any/all Specifications that need them.

We can't necessarily just say `UseQueryFrom` because it could include Skip, Take, OrderBy and other elements that don't combine, in addition to the aforementioned issue with not keeping query logic encapsulated in the domain model in specific specifications.

Hope that makes sense and even if you don't agree, you can see where we're coming from.

**Comment by jvmlet** [comment]
I probably did not express myself properly, by `query` I meant `where clause` only, which  is combined by `AND`.
From client perspective, the `SearchCriteria` UI component might have `area 2` that powers `Spec2`,
`area 3` that powers `Spec3` that might be used independently, and global area that combines both UI components.
*Your last comment is probability answers what I'm after

**Comment by fiseni** [comment]
Having extensions to the specification builder will be a good fit for that. We have more examples under "samples"
 folder in the repository. We tried to cover multiple scenarios in those examples. Let us know if you need further assistance.

**Comment by jvmlet** [comment]
Please criticize :
````c#

public static class SpecificationFilterExtensions {
    public static ISpecificationBuilder<T> WithFiltersOf<T>(
        this ISpecificationBuilder<T> specificationBuilder, ISpecificationBuilder<T> filters) {
        var targetSpec = specificationBuilder.Specification;
        var sourceSpec = filters.Specification;

        var targetWhereExpressions = (List<WhereExpressionInfo<T>>) targetSpec.WhereExpressions;

        foreach (var whereExpressionInfo in sourceSpec.WhereExpressions) {
            targetWhereExpressions.Add(whereExpressionInfo);
        }


        var targetSearchExpressions = (List<SearchExpressionInfo<T>>) targetSpec.SearchCriterias;

        foreach (var searchExpressionInfo in sourceSpec.SearchCriterias) {
            targetSearchExpressions.Add(searchExpressionInfo);
        }

        return specificationBuilder;
    }
}

````

**Comment by fiseni** [comment]
Hey @jvmlet,

Yes, that's the idea. But, as I mentioned, we have exposed the builder publicly, so you don't have to deal with internals and you can write it more cleanly.

```csharp
public static class SpecExtensions
{
    public static ISpecification<T> AddFiltersFrom<T>(
          this ISpecification<T> spec, ISpecification<T> otherSpec) where T : class
    {
        foreach (var whereExpressions in otherSpec.WhereExpressions)
        {
            spec.Query.Where(whereExpressions.Filter);
        }

        foreach (var searchExpressions in otherSpec.SearchCriterias)
        {
            spec.Query.Search(searchExpressions.Selector, searchExpressions.SearchTerm, searchExpressions.SearchGroup);
        }
        return spec;
    }
}
```

The usage will be as follows. I also changed the method name to `AddFiltersFrom` to indicate that the original specification will be updated.

```csharp
var spec1 = new Spec1();
var spec2 = new Spec2();

spec1.AddFiltersFrom(spec2);
```

So, as shown above, it's trivial to implement such composition (at least combining, e.g., AND logic). We do not necessarily want this out of the box, since we do believe it will create ambiguity and a lot of implicit conventions. But, we won't prevent you from doing it by yourself and will provide the necessary mechanisms. I think it's a fair compromise.

PS. Bear in mind that all search expressions within the same group are OR'ed.

**Comment by jvmlet** [comment]
Thanks a lot for your support, @fiseni, very much appreciated.

**Comment by fiseni** [comment]
Hi @LiptonDev,

The example you provided `UserSpec.FindById(1) && UserSpec.NotBlocked && UserSpec.HasRole("admin")` doesn't make much sense to me. This is not about combining/composing specs, but you want some arbitrary behavior on top of a given spec.

Please check answers on this thread, and let us know if you have further questions.

**Comment by jvmlet** [comment]
@fiseni , one more question. What would be the right way to combine specifications  with  `OR` ? 

  spec A :  field1.Equals(1) and  field2.Equals(3)
  spec B :  field3.Equals(3) and  field4.Equals(4)

The resulting spec  should be  ` field1.Equals(1) and  field2.Equals(3)` OR  `field3.Equals(3) and  field4.Equals(4)`

**Comment by LiptonDev** [comment]
@fiseni Hello. Okay, I'm testing this. but I think that this will not suit me, most likely. Thanks for answers.

**Comment by fiseni** [comment]
@jvmlet Well, that's the issue with composite specifications. You start with `And`, then you need `Or`, then `Not`, etc. As I stated in this [response](https://github.com/ardalis/Specification/issues/254#issuecomment-1065866577), it defies the purpose. Back in the day, it was appealing since we didn't have good expressiveness in languages.

>If you start combining the specs all over your code, how is that different than just simply using LINQ all over the place? Not saying that using LINQ everywhere is bad per se, it's your choice. But, probably you started to use specs to avoid doing that in your code. So, it defies the purpose somehow.

Anyhow, here is an example implementation for `Or`. You can run the example and inspect the content of the `newSpec`.

```csharp
using Ardalis.Specification;
using System.Linq.Expressions;
using System.Reflection.Metadata;

var spec1 = new CustomerSpec1();
var spec2 = new CustomerSpec2();

var newSpec = spec1.Or(spec2);

Console.WriteLine();

class CustomerSpec1 : Specification<Customer>
{
    public CustomerSpec1()
    {
        Query.Where(y => y.Field1 == 1)
            .Where(x => x.Field2 == 2);
    }
}

class CustomerSpec2 : Specification<Customer>
{
    public CustomerSpec2()
    {
        Query.Where(y => y.Field3 == 3)
            .Where(x => x.Field4 == 4);
    }
}

class EmptySpecification<T> : Specification<T> { }

class Customer
{
    public int Field1 { get; set; }
    public int Field2 { get; set; }
    public int Field3 { get; set; }
    public int Field4 { get; set; }
}

public static class SpecificationExtensions
{
    public static ISpecification<T> Or<T>(this ISpecification<T> spec, ISpecification<T> otherSpec)
    {
        var newSpec = new EmptySpecification<T>();

        var parameter = Expression.Parameter(typeof(T), "x");

        var exprSpec1 = CombineWhereExpressions(spec.WhereExpressions, parameter);
        var exprSpec2 = CombineWhereExpressions(otherSpec.WhereExpressions, parameter);

        Expression? orExpression = exprSpec1 is not null && exprSpec2 is not null
            ? Expression.OrElse(exprSpec1, exprSpec2)
            : exprSpec1 ?? exprSpec2;

        if (orExpression is null) return newSpec;

        var lambdaExpr = Expression.Lambda<Func<T, bool>>(orExpression, parameter);

        newSpec.Query.Where(lambdaExpr);

        return newSpec;
    }

    public static Expression? CombineWhereExpressions<T>(IEnumerable<WhereExpressionInfo<T>> whereExpressions, ParameterExpression parameter)
    {
        Expression? newExpr = null;
        foreach (var where in whereExpressions)
        {
            var expr = ParameterReplacerVisitor.Replace(where.Filter.Body, where.Filter.Parameters[0], parameter);
            newExpr = newExpr is null ? expr : Expression.AndAlso(newExpr, expr);
        }
        return newExpr;
    }
}

public class ParameterReplacerVisitor : ExpressionVisitor
{
    private readonly Expression _newExpression;
    private readonly ParameterExpression _oldParameter;

    private ParameterReplacerVisitor(ParameterExpression oldParameter, Expression newExpression)
    {
        _oldParameter = oldParameter;
        _newExpression = newExpression;
    }

    internal static Expression Replace(Expression expression, ParameterExpression oldParameter, Expression newExpression)
      => new ParameterReplacerVisitor(oldParameter, newExpression).Visit(expression);

    protected override Expression VisitParameter(ParameterExpression p)
      => p == _oldParameter ? _newExpression : p;
}
```

The resulting specification will contain one `WhereExpression` with the following content

```csharp
Filter = {x => (((x.Field1 == 1) AndAlso (x.Field2 == 2)) OrElse ((x.Field3 == 3) AndAlso (x.Field4 == 4)))}
```

@LiptonDev Closing the issue since we don't fully understand your requirements here. Feel free to reopen the issue if you have further clarifications.

**Comment by jvmlet** [comment]
Thanks @fiseni, I'll try to implement the `Specification` over
https://github.com/scottksmith95/LINQKit?tab=readme-ov-file#combining-expressions...

**Comment by fiseni** [comment]
> All I was pointing out is that the way this library was designed, it makes it more cumbersome to use for the if case.

These two usages are intrinsically incompatible. Either you design for queries, or for the classic specifications. There is no middle ground.

Yes, you may have "criteria"-only interface, make it composable, and so on. None of that is important; that's a trivial thing. I think I've mentioned this in previous issues, but let's elaborate once again. The primary issue is the `state`, or the data. Once you decide to design for queries and keep the state as expressions, the implementation for the other usage, at best, will be "mediocre". 

That implementation requires delegates, so you must compile the expressions you have. That's a very expensive process. In case of in-memory collections, we're caching the delegates locally, so somehow you may close an eye to it and consider it kinda acceptable. But, for `IsSatisifedBy` it's terrible. You're compiling expressions just to check a single entity. Forget compiling, just a waste of storing the criteria as an expression. What do you think the size (allocation-wise) of this simple expression is in .NET?

```csharp
Expression<Func<Customer, bool>> criteria = x => x.Age > 18
```

It's 600 bytes. And we're not even capturing anything here, no closures at all. In case of queries, it is totally acceptable since you anyway will create that expression. We're not adding extra overhead for that case.

I hope you understand why I've been so reluctant on this topic. That's why I never even push users to use the `IsSatisfiedBy` feature. You may say who cares, let the users decide if they wanna use it or not. That's not how it works. Not all users know all these intricacies, and they trust us authors to deliver quality work. If you go through the epic for version 9, we were doing tons of work just to save 8 bytes, for instance. So, having some mediocre composite implementation and suggesting consumers use it just doesn't sit well with me personally.

I'll open an issue on this topic in the following period. I'll elaborate on all the problems, and we'll see if there is an interest in this, despite the downsides.

**Comment by julealgon** [comment]
I appreciate you taking the time to elaborate on those reasons @fiseni . 

I'll admit I was not aware expressions consumed _that_ much memory, for one. For whatever reason I never ran a memory benchmark that included them. I'll be extra careful with allocation for raw specs knowing that now.

> I'll open an issue on this topic in the following period. I'll elaborate on all the problems, and we'll see if there is an interest in this, despite the downsides.

Looking forward to that. 

Thanks again.
