### ISSUE TITLE
Ardalis.Specification.EntityFramework6.csproj doesn't target net7.0 or net8.0

### ISSUE THREAD

**Issue by mpickers** [ardalis/Specification#388]
In release 8.0 it looks like net6.0 was added as a target, but net7.0 and net8.0 were not.
```
<TargetFrameworks>net472;net6.0</TargetFrameworks>
```

Looking at the dependencies of this project they are all netstandard 2 or 2.1 targetted so should be compatible with net7.0 and net8.0 and would bring it into line with the other projects targeting the later frameworks...which would be useful for my use case.

Should be able to have target as:
```
<TargetFrameworks>net472;net6.0;net7.0;net8.0</TargetFrameworks>
```

**Comment by ardalis** [comment]
Everything should still work without these, right? I'm still using this package with my net8 apps no problem. If you need it, I'm not opposed to adding it, but what error are you running into?

**Comment by mpickers** [comment]
No specific error at this stage, just reviewing packages we use for net8 compatibility (by way of looking at what target frameworks our nuget dependencies) for what needs attention for migrating from net6 to net8.

Is there some mysterious link that states that net6 and net7 targeted packages

I have noticed that packages that don't explicitly target net8 still seem to work or nuget at least doesn't balk when adding those packages to a net8 project. However, I can't ..but I can't for the life of me figure out why it wouldn't. Looking at this link: 
https://learn.microsoft.com/en-au/dotnet/standard/frameworks

 ..it's sort of what's the point of having a target framework if it just works on newer versions.

**Comment by ardalis** [comment]
@fiseni do you know of any good reason to add more recent framework targets (or not)?

**Comment by fiseni** [comment]
Hi @mpickers,

We're targeting only `net472;net6.0` for the `EntityFramework6` package since there is no reason to do otherwise. For the `EntityFrameworkCore` package we're targeting `net6.0;net7.0;net8.0` just because we're referencing a different major EF version for each of them. As far as the EF6 is concerned, there is no (and will not be) new major version.  

If a given library targets `net6.0` doesn't mean it can be consumed only by `net6.0` projects. It is the minimum required version. The runtime is always backward compatible. So, if you have a `net8.0` project and for some reason, you're still using EF6, you won't have any issues referencing the `Ardalis.Specification.EntityFramework6` NuGet library.

**Comment by mpickers** [comment]
Hi @fiseni,

Greatly appreciate the explanation!

> If a given library targets net6.0 doesn't mean it can be consumed only by net6.0 projects. It is the minimum required version. The runtime is always backward compatible.

This is the part I was missing. It's not obvious from the Microsoft release notes/doco. No doubt it's somewhere.

cheers
Mark
