### ISSUE TITLE
Select query doesnt return TResult object

### ISSUE THREAD

**Issue by Frankofoedu** [ardalis/Specification#39]
Thank you for this library.

I followed the code samples and created a specification class that is supposed to return a view model after querying the database. The 

```
  public class StaffsInTeamSpecification : Specification<AppUser, CompanySettingsStaffVM>
    {
        public StaffsInTeamSpecification(int companyId)
        {
            Query.Select(b => new CompanySettingsStaffVM { Email = b.Email, Id = b.Id, Name = b.FullName, UserType = b.StaffType })
                .Where(b => b.CompanyId == companyId);
        }
    }
```

This is where I used the spec. 

```
 var stSpec = new StaffsInTeamSpecification(companyId);

var staffs = await _userRepository.ListAsync(stSpec);
```

I noticed staffs is still a ` List<AppUser>` class instead of `List<CompanySettingsStaffVM>`. This shows to my understanding that I cant run a select query in my spec class. If this is not the case, please can I get a little guidance on how to run a select query that returns a different object? Thanks

**Comment by fiseni** [comment]
Hi @Frankofoedu,

It seems you don't have the appropriate method overloading for `ListAsync` in your repository (you should have at least `ListAsync` methods). Please refer to the [RepositoryBase](https://github.com/ardalis/Specification/blob/master/ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBase.cs) class offered within this repository as a reference. Please make sure you have the following methods in you repository.

```
public async Task<List<TResult>> ListAsync<TResult>(ISpecification<T, TResult> specification)
{
    return await ApplySpecification(specification).ToListAsync();
}

private IQueryable<TResult> ApplySpecification<TResult>(ISpecification<T, TResult> specification)
{
    return specificationEvaluator.GetQuery(dbContext.Set<T>().AsQueryable(), specification);
}
```

Once you have these methods, then inevitable you will have the `List<CompanySettingsStaffVM>` as an output. It may not parse it correctly, you may get errors/exceptions, however that's what it will try to give you. Since everything is strongly typed,  after these changes, just hover with mouse over the `staffs` and check what's the type.

Other than that, what you really doing is projecting the entities into view models, and that inheritly is in-memory process, and has nothing to do with building DB queries. But that's completely different subject. Please first try the above changes.

**Comment by Frankofoedu** [comment]
Hi, @fiseni  Thanks for the prompt response. You pointed me in the right direction and I have fixed the code. I guess I was still using the old example for my RepositoryBase class. 

I would want to contribute if there is any backlog for you guys. 

Thanks again for this library

**Comment by fiseni** [comment]
Sure, you're more than welcome to contribute. For now, active issues are #14, #33 and #38.
If you have additional suggestions feel free to open an issue and spark a discussion.
