### ISSUE TITLE
How to use join in specification?

### ISSUE THREAD

**Issue by fingers10** [ardalis/Specification#64]
Is there any possibility to use join within specification?

**Comment by fiseni** [comment]
Hi @fingers10 

The 'Include' actually represents a join. Can you elaborate your question?

**Comment by fingers10** [comment]
something like this

```c#
var query = from photo in context.Set<PersonPhoto>()
            join person in context.Set<Person>()
            on photo.PersonPhotoId equals person.PhotoId
            select new { person, photo };
```

**Comment by fiseni** [comment]
Ok, you can do something like this
```
public class PersonSpec : Specification<Person, Tuple<Person, Photo>>
{
    public PersonSpec()
    {
        Query.Include(x => x.Photo);
        Query.Select(x => new Tuple<Person, Photo>(x, x.Photo) );
    }
}
```

I assume you're creating reports. In that case, instead of using specs, you may want to project the query results directly to your report models, DTOs, etc.

If you want to go through the domain model, then I'd simply use `Include(x => x.Photo)` in my spec, and then flatten it while mapping to the UI model. You can do that manually, or you can use Automapper, it supports flattening.

**Comment by fiseni** [comment]
@finger are you OK with this? Any further questions?

**Comment by fingers10** [comment]
@fiseni sorry for the delayed response. I'm yet to check this. I'll check and get back.

**Comment by fiseni** [comment]
Hey @fingers10,
We didn't get an answer from you. I assume the suggestion worked out. If you have any other questions please let us know. Closing the issue for now.
